spring:
  profiles:
    active: prod

#ftp server info
ftp:
  ftp_address: 192.168.1.110
  ftp_port: 21
  ftp_username: root
  ftp_password: root
  ftp_basepath: /
  ftp_export: export
  ftp_knowledge: knowledge